# Unemployment indicators

## Building unemployment indicators from individual tweets

After reaching good classification performance in detecting disclosures about personal labor market situations, we now need to aggregate this individual information to build timely unemployment indicators from Twitter data.

The first step is to agree on a classification threshold to determine which tweets are positives and negatives. To choose this threshold, we rely on the labelled tweets sampled along the confidence score distribution, as described in the previous part.

Once the cutoff is defined, for a given class, we can isolate tweets considered as positives, that is with a confidence score above the cutoff score previously defined. Using this information, we can then determine the number of users with positive tweets for a given month and year, location, gender, etc... After storing the confidence scores for each tweet in the dataframe `tweet_scores` and for a given class `class_` and `cutoff`:

```{python eval=FALSE}
tmp = tweet_scores.filter(tweet_scores[class_] >= cutoff).groupby('year', 'month', 'user_location', 'gender').agg(
    F.countDistinct("user_id").alias(class_))
```
More information about these unemployment indicators, including data and code, can be found in `SDG-big-data/twitter-analytics/twitter-indicator`.




