# Data {#data}

The complex task of analysing mobility data given the socioeconomic background of the user requires multiple data sources
because we need a type of data that allow us to study individual spatio-temporal behavior, another one with demographic and
economic information and one to serve as a bridge to the other two.

## GPS Data

Anonymous raw GPS points are provided at a global scale by the *Veraset* data company in the framework
of the World Bank “Monitoring COVID-19 policy response through human mobility data” project.
Veraset Movements data consists of raw GPS point information from devices all around the World.
In contrast to the majority of GPS data providers, Verasets Movements are sourced from thousands of
Software Development Kit (SDK) to reduce sample biases.
It features a coverage of about 5\% of the global population.
In our work, unique-device GPS points are processed and analysed as a proxy of individuals mobility and patterns of visits.
The data at our disposal spans over a period of 17 months, starting from the start of Jan 2020 until the end of May 2021.
In this work multiple countries were analysed to assess the impact of the pandemic and the policy responses across a vast
spectrum of potentially different behaviours.


## Wealth Index Data

Aiming for universal behaviors is a hard endeavour as there are cultural and economic differences between every country.
This is why we need an homologated number or index that can describe the level of marginalization or deprivation of goods
that comprise the universal definition of poverty. In order to do this we gathered the latest census data from each country
and summarized the level of education, the access to health services and household characteristics and the finest administrative
unit level available. Then we take all of these values and embed them in a new coordinate system given by a Principal component
Analysis (PCA) and take the normalized value of the first component as a proxy to wealth. This approach yields a continuous variable
which we later discretize by quantiles.

## Administrative Boundaries Data

The country-wise geographical information is given in the form of spatial databases that represent certain areas
with polygons made of vertices in a given cartographic projection, commonly represented by their longitude and latitude
coordinate pair. These areas have labels that can be linked to the census data allowing us to get a spatial representation
of the previously mentioned Wealth Index. These files are usually given by the Statistics or Geography Institute of each nation.
Using Geographical Information Software (GIS), in this case Sedona for Spark, we are able to assign a geographical area to
each one of the GPS points given by the *Veraset* dataset and which will allow us to determine a probable home location
inside an administrative polygon to each user and assign a wealth category to them.
