# (PART\*) GPS Analytics {-}
# Introduction - GPS {#gps}

In latest years new sources of data have been proven to be valuable assets to understand human behavior and thus
help in the creation of public policies based on evidence. Among those lies mobile phone data which is commonly used
to study spatio-temporal patterns in the form of mobility or social connections. This type of data usually comes in two
flavors; Call Detail Record (CDR), which is basicaly the information generated by a telecom transaction between at least two
devices, i.e. phone calls or SMS and it can be used to determine connections between users and a location proxy given the
connection of the device to the nearest antenna. The second type is GPS data. In present times mobile phones, particularely smart phones,
which global penetration is estimated to be almost 50\%, are used for much more than Pier to Pier (P2P) transactions as they
are capable of connecting to the internet through apps. There are companies that partner up with app creators in order to
store information about the usage of their products, this way when used in a phone they store a token with a unique device ID
and time stamp plus any extra information that the user has consent to share, such as geolocation which is obtained via the
high precision GPS anthenas the phones are equiped with plus WiFi triangulation in some cases to upscale it.

We are interested in the latter source of information as the aim of our study is to untangle the universal disparities, if any,
in mobility reduction during the COVID-19 pandemic between socioeconomic groups. We focused our study in 6 middle-income countries (Brazil, Colombia,
Indonesia, Mexico, Philippines and South Africa).