# Geocode {#geocode}

One of the first step in our pipeline is to associate to each point of a gps trace for a user or an user's stop location
the smallest administrative unit available
in our shapefiles for one country. 
This will allow us to join the gps data with the census
and other indices based on the same shapefiles, and to group by larger administrative units (such
as city or region for more general analysis. We will refer to the process of associating a (latitude,longitude) tuple to a shape (corresponding usually to the smallest availabe admin division)
as geocoding.

In this example, we will show how this can be done for the single pings that compose an user's 
GPS trace, but the procedure is exactly the same for the stop locations case described in \@ref(stops)

// The data we are utilizing was provided by Veraset. If a user has installed one of the Veraset's
// partners' apps on his or her mobile phone, the users' position and position's accuracy is sent to the Veraset server where
// it is recorded at regular intervals. 

## Efficient spatial joining and Geospatial Indexing
To be able to deal with billions of points, we need an efficient way to perform spatial queries. Since it is not feasible
to join directly thousands of shapes with the billions of points, for computational reasons, we need an efficient way to reduce the
computational cost by checking only few shapes that are in the surroundings of the point we want to join.
As geo-spatial index we use the [H3](https://eng.uber.com/h3/) indexing created by Uber which partitions the World in hexagons.
Since the admin shapes cannot be exactly covered by hexagons that are included in the shape. The hexagon should have a size
that is reasonable for a quick spatial join and hence be quite large: this implies we
run the risk of mis-joining pings that end up close to the borders of the shapes.

// TODO: put an image or create one

To overcome this problem we perform two joins: the first one will use a geospatial index, and will get the shapes that are close enough to
the points we want to geocode, after buffering the shapes to be sure that any hexagon that is around the border of a shape
is included in the join. The second join will be only between these subsets of shapes selected and the actual point. This greatly
reduces the computational cost and makes this problem tractable.



```{r h3fig, fig.cap='H3 indexing representation. Figure taken from the H3 website referenced above.', out.width='80%', fig.asp=.75, fig.align='center', echo=FALSE}
img <- png::readPNG("figures/h3.png")
grid::grid.raster(img)
```

## Code


### Loading administrative units

We first load the administrative files containing the polygons and the wealth index information, then, using *Apache Sedona* (previously named GeoSpark) we
can transform the Well-Known Text representation of the polygons (WKT) into geometries and create a buffer around them.

```{scala eval=FALSE}
var admin = spark.read.option("header","true").csv(c("admin_path") + "/" + c("country") + "/admin.csv")
admin.createOrReplaceTempView("admin")


var query = "SELECT geom_id AS geom_id, ST_GeomFromText(geometry) as polygon FROM admin"
admin = spark.sql(query)
admin.createOrReplaceTempView("admin_with_polygons")


query = "SELECT *, ST_Buffer(polygon, 0.005) as polygon_buff FROM admin_with_polygons"
admin = spark.sql(query)
```

### Loading ping data and h3 indexing

We will also be needing the ping data from *Veraset*. In our case we'll load them from the following table depending on the country.

```{scala eval=FALSE}
val table = s"pings.${c("source")}_${c("country")}"
```

Then we're able to proceed indexing the pings and the buffered geometries.
In order to do this we only take those pings that have correct longitude and latitude
values and threshold the accuracy (provided in the data) of the GPS point location. That last part is a confidence
estimate of the real location of the device, we can usually see this in our phone when using a geolocation app which
gives you information such as "accuracy < 3m" which means that the actual position could be anywhere in a 3m radius circle with
center at the position given.

When reading the pings, we first filter the ones having wrong coordinates or an accuracy > than 1km, and add to the spark
table a column containing the county's offset (if a country has only one timezone), since we want to compare different
countries for the same time of the days, we will use this offset to align all the timestamps. We then index each buffered
admin shape and ping using h3.
```{scala eval=FALSE}
var pings = spark.sql(s"SELECT lat, lon, accuracy, timestamp AS time, device_id AS user_id FROM ${c("input_table")} WHERE country = '${c("country")}'")
pings.filter($"lat" > -90 && $"lat" < 90 && $"lon" > -180 && $"lon" < 180 && $"accuracy" >= 0 && $"accuracy" <= 1000)
if (c("country") == "CO"){
  pings = pings.withColumn("offset", lit(-5*60*60)) //colombia offset
  pings.printSchema()
}

val res = 10
pings = pings.withColumn("time", col("time") + col("offset")).withColumn("h3index", geoToH3(col("lat"), col("lon"), lit(res)))

val adminH3 = admin.withColumn("h3index", multiPolygonToH3(col("polygon_buff"), lit(res))).select("geom_id", "h3index").withColumn("h3index", explode($"h3index"))

pings.createOrReplaceTempView("pingsH3")
adminH3.createOrReplaceTempView("adminH3")
```
## Initial coarse geo-spatial join with shapefiles
We then perform the first approximated spatial join using the spatial index and write it on an intermediate table

```{scala eval=FALSE}
val query = """SELECT p.time
                    , p.user_id
                    , p.lat
                    , p.lon
                    , p.accuracy
                    , s.geom_id
                FROM pingsH3 AS p
                INNER JOIN adminH3 AS s
                ON (p.h3index = s.h3index)"""

var pings_geocoded = spark.sql(query)

val out_table_temp = s"pings.${c("source")}_${c("country")}_geocoded_temp"
pings_geocoded.write.format("delta").mode("overwrite").saveAsTable(out_table_temp)
```

## Final exact join with a subset of the shapefiles
Finally perform the accurate spatial join on the reduced subset of shapes and pings without the spatial index and save it.

```{scala eval=FALSE}
val out_table_temp = s"pings.${c("source")}_${c("country")}_geocoded_temp"

val admin = spark.sql(s"select geom_id, polygon from admin_with_polygon")
val pings_geo = spark.read.table(out_table_temp)
var pings_geo_pol = pings_geo.join(broadcast(admin), on='geom_id')
pings_geo_pol.createOrReplaceTempView("pings_geo")

val query = "SELECT *, ST_Point(cast(lon as Decimal(13,10)), cast(lat as Decimal(13,10))) as point FROM pings_geo"
pings_geo_pol = spark.sql(query)
pings_geo_pol.createOrReplaceTempView("pings_geo")

val query = "SELECT * FROM pings_geo WHERE ST_Intersects(point, polygon)"
pings_geo_pol = spark.sql(query).drop("polygon", "point", "valid")

val out_table_temp = s"pings.${c("source")}_${c("country")}_geocoded"
pings_geo_pol.write.format("delta").mode("overwrite").saveAsTable(out_table)
```