# (PART\*) Twitter Analytics - News {-}
# Introduction - News Analytics {#news}

We take news articles focusing on a specific country and compute the sentiment associated with the article. The methodology is detailed in [Fraiberger et al. (2021)](https://doi.org/10.1016/j.jinteco.2021.103526) with an application to understanding international asset prices. 

## News articles

Our dataset of news comes from [Factiva.com](https://professional.dowjones.com/factiva/). Articles are indexed using region and subject tags. Each article is annotated with topics and geographic tags generated by Factiva using a proprietary algorithm. Note that an article can be tagged with multiple locations and topics. 

In [Fraiberger et al. (2021)](https://doi.org/10.1016/j.jinteco.2021.103526), we focused on English articles published by Reuters between 1991 and 2015 and tagged with either `economic news` or `financial market news` as well as with one of the 25 countries in our sample (9 AE and 16 EM). In this chapter, we provide an updated version of the news sentiment index based on Reuters articles published between 1991 and 2019. Overall, our dataset covers a wide range of economic topics (e.g. economic policy, government finance, etc.), financial topics (e.g. commodity markets, equity markets, forex, etc.), as well as corporate and political news. 

